config/routes.rb
Rails.application.routes.draw do
 get '/' => "home#index"

 get '/blank' => "home#other"
 get '/publications' => "home#publications"
 get '/contact' => "home#contact"

 root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="boxes zero">
    <div class="main">
            <p><b>A scientist, inventor and serial entrepreneur</b>, Dr. Lauren Barghout holds a Ph.D. and M.S. in Vision Science from the University of California at Berkeley and a Bachelors degree in Physics from Hampshire College. Lauren founded several companies. She invented a Gestalt-based fuzzy-logic image segmentation and labeling technique used commercially in image/video back-ground removal systems, object recognition and image labeling systems. Her research has contributed to the understanding of context-dependent spatial vision, spatial masking, theoretical and computational psychophysics, and the application of fuzzy set theory to human and machine vision. She is a visiting scholar at the Berkeley Initiative for Soft Computing in the Electrical Engineering and Computer Science department at U.C. Berkeley. She is currently writing a book for O’Reilly Media titled: "Essential Computer Vision: Fuzzy and Bayesian techniques" with co-author Anthony Di Franco.</p>
 	</div>
        
    <div class="recent">
        	<h3>Publications Of Interest</h3>
            <h4>(click on the links below to download)</h4>

        
        	<a href="/documents/large_document.pdf">Spatial-Taxon Information Granules as Used in Iterative Fuzzy-Decision-Making
            for Image Segmentation</a>
        	<br>
            <br>
        	<a href="/documents/large_document.pdf">Download</a>
        	<br>
            <br>
        	<a href="/documents/large_document.pdf">Download</a>
    </div>
   </div>
</div>

  

app/views/home/other.html.erb
<h1>blank page</h1>

app/views/home/publications.html.erb
<div class="container">
<div class="boxes zero">
<div class="publication">
    
    <h1> Publications</h1>
 
<p>Barghout, Lauren. "Spatial-Taxon Information Granules as Used in Iterative Fuzzy-Decision-Making for Image Segmentation." Granular Computing and Decision-Making. Springer International Publishing, 2015. 285-318. <a href="/documents/large_document.pdf">Download</a></p>
 
<p>Barghout, Lauren. "Visual Taxometric Approach to Image Segmentation Using Fuzzy-Spatial Taxon Cut Yields Contextually Relevant Regions." Information Processing and Management of Uncertainty in Knowledge-Based Systems. Springer International Publishing, 2014.<a href="/documents/large_document.pdf">Download</a></p>




</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaurenB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/header' %>


<%= yield %>


</body>
<footer><h2>Contact</h2>
<p>Lauren.barghout@gmail.com</p></footer>
</html>

app/views/shared/_header.html.erb
<div class= "header">
<h1><%= link_to 'Lauren Barghout Ph.D.', root_path  %>
</h1>

<nav>

<%= link_to 'Publictions', publications_path %>
<%= link_to 'Home', root_path  %>
</nav>
</div>
<br>
<br>